name = "hex-hensel-mathlib"
defaultTargets = ["HexHenselMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexHensel"
git = "https://github.com/leanprover/hex-hensel.git"
rev = "e9cdca38baa5b0c9e6449300715cb4defc342f9c"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "d4bbb82b87704d3016c6c1d822ae1f77c793958a"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexHenselMathlib"
